### ISSUE TITLE
yo angular2-module not working after installation

### ISSUE THREAD

**Issue by choucry13** [mattlewis92/generator-angular2-module#2]
Hi,
i read your readme. When i want lauch yo angular2-module, it's block here : 

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |      Welcome to the      |
   `---------´   |       awe-inspiring      |
    ( _´U`_ )    | generator-angular2-modul |
    /___A___\    |       e generator!       |
     |  ~  |     '--------------------------'
   __'.___.'__
 ´   `  |° ´ Y `

... and nothing change.
Maybe i forget a step but i'm not sure.
thank

**Comment by choucry13** [comment]
I'm not patient ! Sorry ^^

**Comment by mattlewis92** [comment]
Glad you got it sorted! 😄
